- Gemfile.lock
- app/controllers/alerts_controller.rb
- app/controllers/assignments_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/subscribers_controller.rb
- app/controllers/users_controller.rb
- test/controllers/alerts_controller_test.rb
- test/controllers/assignments_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/subscribers_controller_test.rb
- test/controllers/users_controller_test.rb
The following controllers & views are now added:
- alerts
- assignments
- subscribers
- messages
- users
> Created controllers for every model

- Gemfile
- Gemfile.lock
- app/models/alert.rb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20221119103412_create_active_storage_tables.active_storage.rb
- db/schema.rb
Added Active Storage and Cloudinary to allow for photos on alerts!
> feat: added active storage and cloudinary

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_address_autocomplete.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/controllers/address_autocomplete_controller.js
- app/javascript/controllers/index.js
- app/views/pages/index.html.erb
- package.json
- yarn.lock
Was finally able to add this functionality 😩 Need to work on what else we can include on this page...quite empty.
> Address autocomplete on pages#index

- app/controllers/alerts_controller.rb
- app/controllers/application_controller.rb
- app/controllers/assignments_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/alerts/my_alerts.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- config/routes.rb
Updated the following:
- User login
- User sign up
- User edit settings
- View my alerts (just the barebones functionality, it doesn’t look good since I will use the format & design that @PiotrekCodes and @DariBerrie are working on). Also, this function depends on the ‘Enter new alert’ to test properly. (I think @zynolia is working on that right now). I tested it by tweaking the my_alerts to show those by a faker user.
> Updated: User devise views and functionality, My Alerts views and functionality

- app/controllers/application_controller.rb
- app/models/user.rb
Just added some code to allow user to accept additional attributes at sign up!
> fix: fixed user sign-up

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_new_alert.scss
- app/controllers/alerts_controller.rb
- app/views/alerts/new.html.erb
- app/views/alerts/piotr_new_alerts_html.erb
Please don't judge this, I have so many things to do on this page 😅 But the form itself is working, so we can test the user journey. 
I moved Piotr's new alert file because that should be maybe on the alerts page?
> added new alert form

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- config/environments/production.rb
- config/initializers/default_meta.rb
- config/meta.yml
Just making some additions suggested in the lecture for demoing.
> Demo setup

- app/controllers/alerts_controller.rb
- app/javascript/controllers/alert_show_map_controller.js
- app/javascript/controllers/index.js
- app/views/alerts/show.html.erb
Added alert-show-map js controller and adjusted some of the show view code to make marker appear on map.
> fix: added marker to map.

- app/assets/stylesheets/components/_map.scss
- app/views/alerts/index.html.erb
Alerts sorted in desc order by created_at, link added to create new alert button
> link to create alert added, alerts sorted desc by created_at"

- app/assets/stylesheets/components/_address_autocomplete.scss
- app/assets/stylesheets/components/_new_alert.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/intake/details_controller.rb
- app/views/intake/categories/new.html.erb
- app/views/intake/details/new.html.erb
Changed the style of the form and added autocomplete to the address
> New alert form

- app/views/alerts/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_alert_banner.html.erb
- app/views/shared/_navbar.html.erb
Reverts DariBerrie/ouicity#58 didn't work :(
> Revert "Alert list"

- app/assets/stylesheets/application.scss
footer pushed to bottom of page using flex on body element.
> fix:hopefully fixed the footer position

- app/javascript/controllers/address_autocomplete_controller.js
- app/javascript/controllers/map_controller.js
- app/views/alerts/index.html.erb
- app/views/intake/details/new.html.erb
> fix: address now pre-loaded on alert intake form.

- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_index.scss
- app/channels/chatroom_channel.rb
- app/controllers/chat_messages_controller.rb
- app/controllers/chatrooms_controller.rb
- app/javascript/controllers/chatroom_subscription_controller.js
- app/javascript/controllers/index.js
- app/models/chat_message.rb
- app/models/chatroom.rb
- app/models/user.rb
- app/views/chat_messages/_chatMessage.html.erb
- app/views/chatrooms/show.html.erb
- config/routes.rb
- db/migrate/20221203102345_create_chatrooms.rb
- db/migrate/20221203102557_create_chat_messages.rb
- db/migrate/20221203102627_add_nickname_to_users.rb
- db/schema.rb
- db/seeds.rb
- package.json
- test/channels/chatroom_channel_test.rb
- test/controllers/chat_messages_controller_test.rb
- test/controllers/chatrooms_controller_test.rb
- test/models/chat_message_test.rb
- test/models/chatroom_test.rb
- yarn.lock
Basic chat functionality added, need to workout the way to create chatrooms connected to alerts.
For now, if you want to check functionality, please create chatroom in rails console, it needs a “name” only.
Path is http://localhost:3000/chatrooms/#
> feat: added chat functionality to the app

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/pages/_index.scss
- app/models/alert.rb
- app/models/assignment.rb
- app/views/alerts/edit.html.erb
Added the delete logic to the edit alert page. If the alert has been assigned to a worker, the resident can no longer make edits.
Also added a bit of styling to the form.
> fix: added delete function on page. changed a bit of the form styling.

- app/controllers/alerts_controller.rb
- app/controllers/intake/categories_controller.rb
- app/views/alerts/index.html.erb
adjusted the user authentication on certain pages so that we redirect to the login page instead of the page breaking.
> fix: adjusted user authentication on some pages to redirect

- app/controllers/alerts_controller.rb
- app/controllers/assignments_controller.rb
- app/views/alerts/_city.html.erb
- config/routes.rb
We can assign an alert to a worker, but right now every user will show up in the dropdown list. Will work on this on Thursday
> Show alert

- app/controllers/assignments_controller.rb
- app/views/assignments/index.html.erb
- app/views/shared/_offcanvas.html.erb
- config/routes.rb
Created a view where you can see your assignments and your subscriptions (back end function not yet ready, so this is pulling from the assignments data for now).
> Assignments and Subscriptions page

- app/views/alerts/my_alerts.html.erb
> Updated the My Alerts view to match elsewhere on the site

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_chatroom.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_table.scss
- app/controllers/alerts_controller.rb
- app/controllers/contacts_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/alert.rb
- app/views/alerts/_index_worker.html.erb
- app/views/alerts/_show_worker.html.erb
- app/views/chatrooms/_show.html.erb
- app/views/shared/_offcanvas.html.erb
I made some updates to the index page including pg_search and created a chat partial for the show page using @PiotrekCodes code.
> Worker alerts index

- db/migrate/20221210133950_change_assignments_to_alerts_in_subscribers.rb
- db/schema.rb
> fix: subscribers

- app/views/chatrooms/_show.html.erb
- config/cable.yml
Adding redis production configuration
> fix:adding redis to production

- app/javascript/controllers/chatroom_subscription_controller.js
> fix:chat fix

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/controllers/map_controller.js
- app/views/shared/_navbar.html.erb
Also my previous fix for the double viewing of the geocoder on the alerts index page didn't work, so I made an adjustment to the js controller there.
> fix: navbar no longer toggles, on one line with just icons for mobile view

- app/assets/stylesheets/components/_new_alert.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/javascript/controllers/index.js
- app/views/alerts/_index_resident.html.erb
- app/views/alerts/_show_resident.html.erb
- app/views/alerts/my_alerts.html.erb
- app/views/intake/categories/new.html.erb
- app/views/intake/details/new.html.erb
- app/views/shared/_status_bar.html.erb
Made some additional tweaks to the front end.
@zynolia I noticed that the "back" button on the new alert form doesn't work (it doesn't go anywhere). For now, I've changed it to a link_to button, but I'm not sure if that should really just go back to the category page (where the page would likely be refreshed w/o the chosen category) or if you had another solution in mind.
> Front end cleanup

- app/assets/stylesheets/components/_containers.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_table.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/alerts/_index_worker.html.erb
- app/views/alerts/_show_worker.html.erb
- app/views/alerts/analytics.html.erb
- app/views/shared/_offcanvas.html.erb
Again, just some minor changes to the look of the pages.
> fix:front-end changes to worker pages

- app/controllers/alerts_controller.rb
- app/controllers/intake/details_controller.rb
@zynolia In the Details controller, there doesn't seem to be a if/else statement for the create method that is normally there for if the object saves -> redirect, else render unprocessable...
Should this be there or is it best to leave this out? Is the create method in the alerts controller needed? Thanks!
> fix: chatroom now being created with alert

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/contacts_controller.rb
- app/javascript/controllers/alerts_controller.js
- app/javascript/controllers/typed_js_controller.js
- app/models/contact.rb
- app/views/alerts/_index_resident.html.erb
- app/views/intake/details/new.html.erb
- app/views/layouts/application.html.erb
fix: collapse transitions on alert listings and back button on new alert form
> Smooth scroll alerts
